name: CI&CT-Bookkeeper

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 8 (Amazon Corretto)
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'corretto'
          cache: maven 

      - name: Maven validate
        run: mvn validate

      - name: Build with Maven
        run: mvn clean install
